# generated by datamodel-codegen:
#   filename:  genson_schema_builder.json
#   timestamp: 2024-02-06T00:20:17+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Account(BaseModel):
    id: str
    partitionId: str
    platformType: Optional[str] = None
    routePlanId: Optional[str] = None


class ActingParty(BaseModel):
    userId: str
    username: str
    userType: str
    partitionId: str
    permissions: Optional[Permission]


class Envelope(BaseModel):
    version: float
    id: str
    traceId: str
    dateTime: datetime
    source: str
    shardId: None
    action: str
    interfaces: None


class Forward(BaseModel):
    partitionId: str
    accountId: str
    sipTrunkId: str
    forwardAlways: ForwardAlways
    forwardOnFailure: Optional[List[ForwardOnFailureItem]]
    forwardOnCapacityExceeded: Optional[List[ForwardOnCapacityExceededItem]]


class ForwardAlways(BaseModel):
    enabled: bool
    referenceType: Optional[str] = None
    referenceId: Optional[Union[int, str]] = None


class ForwardOnCapacityExceededItem(BaseModel):
    referenceType: str
    referenceId: str


class ForwardOnFailureItem(BaseModel):
    referenceType: str
    referenceId: str


class Metadata(BaseModel):
    action: str
    objectType: str
    sentTimestamp: int
    arrivalTimestamp: int
    transformTimestamp: int
    streamLag: int
    envelope: Envelope


class ModelCodegen(BaseModel):
    codegen_version: str = Field('0.0.0.2023-10-10~edfc7ed2', const=True)
    id: str
    accountId: str
    partitionId: str
    trunkName: str
    concurrentCalls: int
    extensionPatterns: Optional[List[str]] = None
    forward: Forward
    sipUsername: Optional[str] = None
    sipPassword: Optional[str] = None
    lockedOut: bool
    stirShakenExpandedCallerIdVerification: bool
    account: Account
    actingParty: ActingParty
    eventOn: datetime
    createOn: Optional[datetime]
    deleteOn: Optional[datetime]
    metadata: Metadata
    localServicesEnabled: Optional[bool] = None
    primaryTn: Optional[int] = None
    callbackNumber: Optional[int] = None


class Permission(BaseModel):
    Account: str
    AccountHistory: str
    AccountCallHistory: str
    AccountBulkStatuses: str
    PhoneNumber: str
    PhoneNumberServiceActivation: str
    PhoneNumberInventory: str
    Product: str
    ProductCallingPlan: str
    ProductGroups: str
    ProductUsers: str
    Reports: str
    RoutePlan: str
    SipCredentials: str
    ALIANZA_MasterRoutePlan: Optional[str] = None
    ALIANZA_TogglzAdmin: Optional[str] = None
    ANY_MANAGEMENT_USER: str
    ANY_ALIANZA_USER: Optional[str] = None
